media: files
content:
  - name: posts
    label: Posts
    type: collection
    path: public/posts
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - { name: date, label: Date, type: date }
      - { name: description, label: Description, type: string, options: { maxlength: 160 } }
      - name: contact 
        label: Contact information
        type: object
        fields:
          - name: first_name
            label: First name
            type: string
          - name: last_name
            label: Last name
            type: string
