media: 
  input: public/files
  output: files
content:
  - name: posts
    label: Posts
    type: collection
    path: public/posts
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: slide
        label: Slides
        type: object
        fields:
          - name: slide1
            label: Slide 1
            type: object
            fields:
            - name: slide
              label: slide  title
              type: string
              options: { maxlength: 160 }
            - name: cover
              label: slide  cover
              type: image
              options:
                  path: src/files/images
                  extensions: [ jpg, jpeg, png ]
      - name: features
        label: Features
        type: object
        fields:
          - name: feature1
            label: Feature 1
            type: object
            fields:
            - name: feature
              label: feature  title
              type: string
              options: { maxlength: 160 }
            - name: feature
              label: feature  body
              type: string
              options: { maxlength: 160 }
            - name: feature1
              label: feature  icon
              type: string
              options: { maxlength: 160 }
          - name: feature2
            label: Feature 2
            type: object
            fields:
            - name: feature
              label: feature  title
              type: string
              options: { maxlength: 160 }
            - name: feature
              label: feature  body
              type: string
              options: { maxlength: 160 }
            - name: feature1
              label: feature  icon
              type: string
              options: { maxlength: 160 }
          - name: feature3
            label: Feature 3
            type: object
            fields:
            - name: feature
              label: feature  title
              type: string
              options: { maxlength: 160 }
            - name: feature
              label: feature  body
              type: string
              options: { maxlength: 160 }
            - name: feature1
              label: feature  icon
              type: string
            options: { maxlength: 160 }