media: files
content:
  - name: posts
    label: Posts
    type: collection
    path: public/posts
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - { name: date, label: Date, type: date }
      - { name: description, label: Description, type: string, options: { maxlength: 160 } }
      - name: slide
        label: Slide information
        type: object
        fields:
          - name: ID
            label: ID
            type: string
          - name: body
            label: body
            type: string
            options: { maxlength: 160 }
          - name: image
            label: image
            type: string
           