media: 
  input: public/files
  output: files
content:
  - name: posts
    label: Posts
    type: collection
    path: public/posts
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: slide
        label: Slides
        type: object
        fields:
          - name: slide1
            label: slide 1 body
            type: string
            options: { maxlength: 160 }
          - name: cover1
            label: Cover 1 
            type: image
            options:
              path: src/files/images
              extensions: [ jpg, jpeg, png ]
          - name: slide2
            label: slide 2 body
            type: string
            options: { maxlength: 160 }
          - name: cover2
            label: Cover 2 
            type: image
            options:
              path: src/files/images
              extensions: [ jpg, jpeg, png ]
          - name: slide3
            label: slide 3 body
            type: string
            options: { maxlength: 160 }
          - name: cover3
            label: Cover 3 
            type: image
            options:
              path: src/files/images
              extensions: [ jpg, jpeg, png ]
      - name: features
        label: Features
        type: object
        fields:
          - name: feature1
            label: Feature 1
            type: object
            fields:
            - name: feature
              label: feature  title
              type: string
              options: { maxlength: 160 }
            - name: feature
              label: feature  body
              type: string
              options: { maxlength: 160 }
            - name: feature1
              label: feature  icon
              type: string
            options: { maxlength: 160 }
          - name: feature2
            label: feature 2 title
            type: string
            options: { maxlength: 160 }
          - name: feature2
            label: feature 2 body
            type: string
            options: { maxlength: 160 }
          - name: feature2
            label: feature 2 icon
            type: string
            options: { maxlength: 160 }
          - name: feature3
            label: feature 3 title
            type: string
            options: { maxlength: 160 }
          - name: feature3
            label: feature 3 body
            type: string
            options: { maxlength: 160 }
          - name: feature3
            label: feature 3 icon
            type: string
            options: { maxlength: 160 }
            