media: files
content:
  - name: posts
    label: Posts
    type: collection
    path: public/posts
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: date, label: Date, type: date }
     -  { name: contact, 
          label: Contact information, type: object,
          fields:
            - name: first_name
              name: First name
              type: string
          }