media: 
  input: public/files
  output: files
content:
  - name: posts
    label: Posts
    type: collection
    path: public/posts
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - { name: date, label: Date, type: date }
      - { name: description, label: Description, type: string, options: { maxlength: 160 } }
      - name: cover
        label: Cover
        type: image
        options:
          path: src/files/images
          extensions: [ jpg, jpeg, png ]
      - name: slide
        label: Slide information
        type: object
        fields:
          - name: id
            label: id
            type: string
          - name: body
            label: body
            type: string
            options: { maxlength: 160 }