media: 
  input: public/files
  output: files
content:
  - name: posts
    label: Posts
    type: collection
    path: public/posts
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - { name: date, label: Date, type: date }
      - { name: description, label: Description, type: string, options: { maxlength: 160 } }
      - name: slide
        label: Slides
        type: object
        fields:
          - name: slide1
            label: slide 1 body
            type: string
            options: { maxlength: 160 }
          - name: cover1
            label: Cover 1 
            type: image
            options:
              path: src/files/images
              extensions: [ jpg, jpeg, png ]
          - name: slide2
            label: slide 2 body
            type: string
            options: { maxlength: 160 }
          - name: cover2
            label: Cover 2 
            type: image
            options:
              path: src/files/images
              extensions: [ jpg, jpeg, png ]