media: files
content:
  - name: posts
    label: Posts
    type: collection
    path: public/posts
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: date, label: Date, type: date }
      - { name: items, label: Body, type: rich-text }